//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usersettings_test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>SMS Notifications Enabled,10000000,1,TRUE</string>
  <string>Push Notifications Enabled,01000000,2,TRUE</string>
  <string>Bio-metrics Enabled,00100000,3,TRUE</string>
  <string>Camera Enabled,00010000,4.TRUE</string>
  <string>Location Enabled,00001000,5,TRUE</string>
  <string>NFC Enabled,00000100,6,TRUE</string>
  <string>Vouchers Enabled,00000010,7,TRUE</string>
  <string>Loyalty Enabled,00000001,8,TRUE</string>
  <string>Vouchers Enabled,00000000,0,FALSE</string>
  <string>Camera Enabled,11111111,4,TRUE</string>
  <string>TEST,01111111,4,FALSE</string>
  <string>TEST2,01011111,4,FALSE</string>
  <string>TEST3,01001111,4,FALSE</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection USR_SET {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["USR_SET"]));
            }
            set {
                this["USR_SET"] = value;
            }
        }
    }
}
